### ISSUE TITLE
First row of the grid comes up too long

### ISSUE THREAD

**Issue by Tarrtar** [zofe/rapyd-laravel#207] opened 2015-07-29 14:09 UTC
First row of the grid shows up like the below image when the grid is populated, i am not using any other css class or styling for the grid. I tried to use ```style()``` function to fix this but it didnt work out. What is causing that problem ? Any idea what is going on ? Any help would be appreciated.

![original](https://cloud.githubusercontent.com/assets/6633593/8959597/68ed33ae-3614-11e5-8936-2491de516097.jpg)

```php
public function createVehicleDataGrid($dataSource) {
	$searchGrid = DataGrid::source($dataSource);
	$searchGrid->add('id','Evrak No', true)->style('width:10px;');
	$searchGrid->add('model','Model', true);
	$searchGrid->add('{{@$brand->brand_name}}','Marka', true);
	$searchGrid->add('licenseplate','Plaka', true);
	$searchGrid->add('buying_date','Alış Tarihi', true);
	$searchGrid->add('{{@$seller->full_name }}','Alınan Kişi', true);
	$searchGrid->add('{{@$seller->mobile_number}}','ATEL', true);
	$searchGrid->add('buying_place','Alınan Yer', true);
	$searchGrid->add('{{@$representive->full_name}}','Ruhsat Sahibi', true);
	$searchGrid->add('buying_exchange_definition','Alış-Takas', true);
	$searchGrid->add('selling_date','Satış Tarihi', true);
	$searchGrid->add('{{@$buyer->full_name}}','Satılan Kişi', true);
	$searchGrid->add('selling_place','Satılan Yer Yer', true);
	$searchGrid->add('{{@$buyer->mobile_number}}','STEL', true);
	$searchGrid->add('selling_exchange_brand','Takas Adı', true);
	$searchGrid->add('{{@$section->section_name}}','Araç Nerede', true);
	$searchGrid->add('is_document_ready','Evrak Hazır Mı?', true);
	$searchGrid->add('is_new_document_needed','Yeni Evrak Mı?', true);
	$searchGrid->add('process_situation','İşlem Durumu', true);
	$searchGrid->add('debit_situation','Borç Durumu', true);
	
	$searchGrid->edit('/pages/aracislemler/', 'Göster','show');
	$searchGrid->paginate(7);
	
	$searchGrid->row(function ($row) {
	   
	   if ($row->cell('is_document_ready')->value  == 0) {
		   $row->cell('is_document_ready')->value  = 'Hayır';
	   }else{
		   $row->cell('is_document_ready')->value  = 'Evet';
		   $row->style("background-color:#CCFF66");
	   }
	   
	   if ($row->cell('is_new_document_needed')->value  == 0) {
		   $row->cell('is_new_document_needed')->value  = 'Hayır';
	   }else{
		   $row->cell('is_new_document_needed')->value  = 'Evet';
		   $row->style("background-color:#0000FF");
	   }#FF8C00
	   
	   if ($row->cell('process_situation')->value  == 'Satışı Yapıldı') {
		   $row->style("background-color:#FFD700");
	   }
	   
	   if ($row->cell('process_situation')->value  == 'Mülkiyetli Satışı Yapıldı') {
		   $row->style("background-color:#FF8C00");
	   }
	   
	   if ($row->cell('process_situation')->value  == 'İade') {
		   $row->style("background-color:#696969");
	   }
	   
	   if ($row->cell('debit_situation')->value  == 'Rehinli' || $row->cell('debit_situation')->value  == 'Hacizli') {
		   $row->style("background-color:#B22222");
	   }
	});
	
	return $searchGrid;
}
```

**Comment by zofe** [comment] 2015-07-29 14:52
you can't  add order by column on a "relation" (so you cant use "true" on the last param):
$searchGrid->add('{{@$seller->mobile_number}}','ATEL', true);
this can also contribute to your output problems

**Comment by Tarrtar** [comment] 2015-07-29 14:58
Thanks for the information. I have changed them all to false. But still have the same output problem.

**Comment by zofe** [comment] 2015-07-29 14:59
try to isolate,  add one column at time.. and test output..

**Comment by zofe** [comment] 2015-07-29 15:00
off-topic: about the "huge" number of "if"  in the code, you should take a look to model  "accessors"  in the eloquent documentation, to reduce your code..
for example you can do a single accessor that return the correct color for the "row" and use it only once.

**Comment by Tarrtar** [comment] 2015-07-29 15:05
Thanks for the suggestion, i will try to implement it to reduce the code and will test the output issue again.

**Comment by Tarrtar** [comment] 2015-07-29 15:13
Tried the grid with only one column, still having the same problem which drives me crazy :)

**Comment by zofe** [comment] 2015-07-29 16:53
maybe some html/bootstrap problem..  try to print only the grid and not the filter.

**Comment by Tarrtar** [comment] 2015-07-30 08:13
Still the same. Very strange problem.

**Comment by zofe** [comment] 2015-07-30 08:27
->style('width:10px;');  ?

**Comment by Tarrtar** [comment] 2015-07-30 08:29
I tried this already. Didnt work.

**Comment by zofe** [comment] 2015-07-30 08:29
a <div style="clear: both"></div> before grid output?

**Comment by zofe** [comment] 2015-07-30 08:31
however try to change the view  just to see if the problem is related to some css conflict

**Comment by Tarrtar** [comment] 2015-07-30 08:38
Will try and let you know, thanks.

**Comment by zofe** [comment] 2015-09-21 16:46
not replicable for me, I've to close this.

**Closed by zofe** 2015-09-21 16:46 UTC
